name: Test and Upload Coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run commands
        run: |
          pip install poetry==1.8.2
          poetry config virtualenvs.create false
          poetry install --with dev
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rik-ee/fastapi-xroad-soap
